version: 2.1
jobs:
  test:
    docker:
      - image: docker:stable
        
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - ""
  deploy:
    docker: 
      - image: 
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_ACCESS_TOKEN
    steps:
#      - run:
#           name: Login to dockerhub
#           command: 
      - run:
          name: ssh to ec2 and run the Image
          command: |
              ssh -o "StrictHostKeyChecking no" -i "labsuser 4.pem" ubuntu@ec2-35-91-142-179.us-west-2.compute.amazonaws.com " sudo docker run -d -p 80:80 --name coffeeApp aseelibrahimm/coffee-shop:lts"
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires: 
            - test
