version: 2.1
jobs:
  test:
    docker:
      - image: docker:stable
        
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "ea:a0:16:11:69:50:01:10:ec:74:bd:21:d2:ab:ff:07"
  deploy:
    docker: 
      - image: docker:stable
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - run:
          name: ssh to ec2 and run the Image
          command: |
               ssh -o "StrictHostKeyChecking no" -i "labsuser 4.pem" ubuntu@35.90.94.5 " ssh -o 'StrictHostKeyChecking no' -i 'labsuser 4.pem' ubuntu@10.0.2.135 ' sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin'"
              
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires: 
            - test
